/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package tst.reflection

import com.intellij.DynamicBundle

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    DynamicBundle.INSTANCE
    println(App().greeting)
}
