/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.5/userguide/building_java_projects.html
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.7.20"

    id("org.jetbrains.intellij") version "1.13.3"

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

val intellij_version = "202.8194.7"

intellij {
    version.set(intellij_version)
    type.set("IC")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    maven(url="https://www.jetbrains.com/intellij-repository/releases")
    maven(url="https://cache-redirector.jetbrains.com/intellij-dependencies")
}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    runtimeOnly("com.jetbrains.intellij.platform:core-impl:${intellij_version}")

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:31.0.1-jre")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
}

application {
    // Define the main class for the application.
    mainClass.set("tst.reflection.AppKt")
}
